### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by tky823** [Rsalganik1123/LARP#1]
I have one question about the pretrained model.
In `README.md`, one of the checkpoints `/home/xhliu/KDD2024-LARP` is unavailable. How can I access this model?

Anyway, thank you for sharing the implementation!

**Comment by Rsalganik1123** [comment]
Apologies :) the checkpoints are located at: https://huggingface.co/Rsalga/LARP/tree/main 
We'll update the README to reflect this 

Thanks for using our model!
